package main

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"log/slog"
	"mime"
	"time"

	"github.com/emersion/go-imap/v2"
	"github.com/emersion/go-imap/v2/imapclient"
	"github.com/emersion/go-message/mail"
)

// message
type Mailbox struct {
	ID             int    `json:"id"`
	ServerHostport string `json:"server_hostport"` // so for migadu it would be "imap.migadu.com:993"
	Username       string `json:"username"`        // email addr
	Password       string `json:"-"`               // the - makes it so that it will NOT be included in JSON output
	PrimaryInbox   string `json:"primary_inbox"`   // e.g. "INBOX"
}

type Email struct {
	ID      int      `json:"id"`      // serial
	Mailbox *Mailbox `json:"mailbox"` // fk to Mailbox
	// data pulled from the imap server
	UID         uint32    `json:"-"` // unique identifier
	MessageID   string    `json:"-"`
	Subject     string    `json:"subject"`
	FromAddress string    `json:"from_address"`
	Body        string    `json:"body"`
	RecievedAt  time.Time `json:"received_at"`
}

func syncMailbox(ctx context.Context, db *DB, mailbox Mailbox) error {
	client, err := imapclient.DialTLS(mailbox.ServerHostport, nil)
	if err != nil {
		return fmt.Errorf("connect to imap server: %w", err)
	}
	defer client.Close()

	// login
	cmd := client.Login(mailbox.Username, mailbox.Password)
	if err := cmd.Wait(); err != nil {
		return fmt.Errorf("login to imap server: %w", err)
	}
	defer client.Logout() // it'll log out first and then close client bc defer is lifo

	// select the primary inbox
	selectCmd := client.Select(mailbox.PrimaryInbox, nil)
	selectedInbox, err := selectCmd.Wait()
	if err != nil {
		return fmt.Errorf("select inbox: %w", err)
	}
	if selectedInbox.NumMessages == 0 {
		slog.Info("no msgs in inbox", "mailbox", mailbox.ID)
		return nil // nothing to sync
	}

	// get the last synced UID (we're syncing from the last uid + 1 to the end of the mailbox)
	lastSyncedUID, err := db.GetLastSyncedUID(ctx, nil, mailbox.ID)
	if err != nil {
		return fmt.Errorf("get last synced UID: %w", err)
	}

	if selectedInbox.UIDNext > 0 && imap.UID(lastSyncedUID) >= selectedInbox.UIDNext-1 {
		slog.Info("all messages are already synced", "mailbox", mailbox.ID)
		return nil // all messages are already synced
	}

	var searchCriteria imap.SearchCriteria
	searchCriteria.UID = []imap.UIDSet{
		[]imap.UIDRange{
			{Start: imap.UID(lastSyncedUID + 1), Stop: 0}, // 0 means latest here
		},
	}

	uids, err := client.UIDSearch(&searchCriteria, nil).Wait()
	if err != nil {
		return fmt.Errorf("UID search failed: %w", err)
	}

	if len(uids.AllUIDs()) == 0 {
		slog.Info("no new emails to sync", "mailbox", mailbox.ID)
		return nil
	}

	fetchOptions := &imap.FetchOptions{
		UID: true,
		BodySection: []*imap.FetchItemBodySection{
			{}, // empty specifier fetches the full raw message "To fetch the whole body of a message, use the zero FetchItemBodySection:"
		},
	}

	fetchCmd := client.Fetch(imap.UIDSetNum(uids.AllUIDs()...), fetchOptions)
	defer fetchCmd.Close()

	// the following loop was partially generated by AI
	for {
		msg := fetchCmd.Next()
		if msg == nil {
			break
		}

		var emailUID uint32
		var bodyData []byte

		// need to capture the uid and the body reader for the actual mail
		for {
			item := msg.Next()
			if item == nil {
				break
			}
			switch v := item.(type) {
			case imapclient.FetchItemDataBodySection:
				bodyReader := v.Literal
				bodyData, err = io.ReadAll(bodyReader)
				if err != nil {
					slog.Error("couldn't read body data", "mailbox", mailbox.ID, "uid", emailUID, "error", err)
					continue
				}
			case imapclient.FetchItemDataUID:
				emailUID = uint32(v.UID)
			}
		}
		if bodyData == nil {
			slog.Error("no body data", "mailbox", mailbox.ID, "uid", emailUID)
			continue
		}

		// parse mime envelope using github.com/emersion/go-message
		mr, err := mail.CreateReader(bytes.NewReader(bodyData))
		if err != nil {
			slog.Error("couldn't parse MIME for message", "mailbox", mailbox.ID, "uid", emailUID, "error", err)
			continue
		}

		header := mr.Header
		// note: maybe look at these errors
		subject, _ := header.Subject()
		msgID, _ := header.MessageID()
		from, _ := header.AddressList("From")

		senderStr := ""
		if len(from) > 0 {
			senderStr = from[0].String()
		}

		// read body
		var bodyText string
		for {
			part, err := mr.NextPart()
			if err == io.EOF {
				break
			} else if err != nil {
				break
			}

			// using this bc of bs like "text/plain charset=utf-8" like shut up pls; but uh yeah standard processing
			ct, _, err := mime.ParseMediaType(part.Header.Get("Content-Type"))
			if err != nil {
				slog.Error("couldn't parse content type", "mailbox", mailbox.ID, "uid", emailUID, "error", err)
				continue
			}
			if ct == "text/plain" || ct == "text/html" {
				b, _ := io.ReadAll(part.Body)
				bodyText = string(b)
			} else {
				slog.Warn("unexpected content type", "mailbox", mailbox.ID, "uid", emailUID, "content_type", part.Header.Get("Content-Type"))
			}
		}

		dt, err := header.Date()
		if err != nil {
			slog.Error("couldn't get date for message", "mailbox", mailbox.ID, "uid", emailUID, "error", err)
			continue
		}

		// push to db
		err = db.InsertEmailandUpdateLastSyncedUID(ctx, Email{
			Mailbox:     &mailbox,
			UID:         emailUID,
			MessageID:   msgID,
			Subject:     subject,
			FromAddress: senderStr,
			Body:        bodyText,
			RecievedAt:  dt,
		})
		if err != nil {
			slog.Error("couldn't push email to db", "mailbox", mailbox.ID, "uid", emailUID, "error", err)
		}
	}
	return nil
}
